### ISSUE TITLE
pyCUDAHandler makes problems while training (CPU version works fine)

### ISSUE THREAD

**Issue by dlueder** [IDSIA/brainstorm#117]
Today i installed brainstorm on Arch Linux. Everything fine, but the when i start an example i get this output. 
I'm new, but why does it not work ? :) 
Thank you

 - - - - - - - - - -  Before Training  - - - - - - - - - -
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/brainstorm/training/trainer.py", line 162, in _call_hook
    stepper=self.stepper, logs=self.logs), False
  File "/usr/lib/python3.5/site-packages/brainstorm/hooks.py", line 422, in __call__
    return evaluate(net, self.iter, self.scorers)
  File "/usr/lib/python3.5/site-packages/brainstorm/tools.py", line 77, in evaluate
    network.forward_pass()
  File "/usr/lib/python3.5/site-packages/brainstorm/structure/network.py", line 430, in forward_pass
    layer.forward_pass(self.buffer[layer_name], training_pass)
  File "/usr/lib/python3.5/site-packages/brainstorm/layers/loss_layer.py", line 46, in forward_pass
    buffers.outputs.loss.reshape(tuple()))
  File "/usr/lib/python3.5/site-packages/brainstorm/handlers/pycuda_handler.py", line 379, in sum_t
    cumisc.sum(a.reshape((a.size, 1)), axis=0, out=out)
  File "/usr/lib/python3.5/site-packages/skcuda/misc.py", line 1266, in sum
    return _sum_axis(x_gpu, axis, out=out, keepdims=keepdims)
  File "/usr/lib/python3.5/site-packages/skcuda/misc.py", line 1225, in _sum_axis
    ons = ones((sum_axis, ), x_gpu.dtype, alloc)
  File "/usr/lib/python3.5/site-packages/skcuda/misc.py", line 448, in ones
    out = gpuarray.GPUArray(shape, dtype, allocator, order=order)
  File "/usr/lib/python3.5/site-packages/pycuda/gpuarray.py", line 193, in __init__
    raise ValueError("invalid order: %s" % order)
ValueError: invalid order: <Boost.Python.function object at 0x1932690>

**Comment by dlueder** [comment]
`

 - - - - - - - - - -  Before Training  - - - - - - - - - -
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/brainstorm/training/trainer.py", line 162, in _call_hook
    stepper=self.stepper, logs=self.logs), False
  File "/usr/lib/python3.5/site-packages/brainstorm/hooks.py", line 422, in __call__
    return evaluate(net, self.iter, self.scorers)
  File "/usr/lib/python3.5/site-packages/brainstorm/tools.py", line 77, in evaluate
    network.forward_pass()
  File "/usr/lib/python3.5/site-packages/brainstorm/structure/network.py", line 430, in forward_pass
    layer.forward_pass(self.buffer[layer_name], training_pass)
  File "/usr/lib/python3.5/site-packages/brainstorm/layers/loss_layer.py", line 46, in forward_pass
    buffers.outputs.loss.reshape(tuple()))
  File "/usr/lib/python3.5/site-packages/brainstorm/handlers/pycuda_handler.py", line 379, in sum_t
    cumisc.sum(a.reshape((a.size, 1)), axis=0, out=out)
  File "/usr/lib/python3.5/site-packages/skcuda/misc.py", line 1266, in sum
    return _sum_axis(x_gpu, axis, out=out, keepdims=keepdims)
  File "/usr/lib/python3.5/site-packages/skcuda/misc.py", line 1225, in _sum_axis
    ons = ones((sum_axis, ), x_gpu.dtype, alloc)
  File "/usr/lib/python3.5/site-packages/skcuda/misc.py", line 448, in ones
    out = gpuarray.GPUArray(shape, dtype, allocator, order=order)
  File "/usr/lib/python3.5/site-packages/pycuda/gpuarray.py", line 193, in __init__
    raise ValueError("invalid order: %s" % order)
ValueError: invalid order: <Boost.Python.function object at 0x1932690>

`

**Comment by dlueder** [comment]
Changed my OS to Ubuntu 16.04 LTS. 
Now it works!
