### ISSUE TITLE
Cannot import brainstorm

### ISSUE THREAD

**Issue by mAch17** [IDSIA/brainstorm#63]
I ran pip install -r requirements and python setup.py install
Here is what I see : 

>>> import brainstorm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "brainstorm\__init__.py", line 6, in <module>
    from brainstorm.structure import Network, generate_architecture
  File "brainstorm\structure\__init__.py", line 4, in <module>
    from brainstorm.structure.network import Network
  File "brainstorm\structure\network.py", line 13, in <module>
    from brainstorm.handlers import default_handler
  File "brainstorm\handlers\__init__.py", line 4, in <module>
    from brainstorm.handlers.numpy_handler import NumpyHandler
  File "brainstorm\handlers\numpy_handler.py", line 7, in <module>
    from brainstorm.handlers import _cpuop
ImportError: cannot import name _cpuop

**Comment by flukeskywalker** [comment]
Perhaps you are trying to import brainstorm while  in the ``brainstorm`` directory? Try changing the directory.

If you'd like to import it in the ``brainstorm`` directory, you should do ``python setup.py build_ext --inplace`` first.

**Comment by mAch17** [comment]
yes, that was the problem. It works now. Thanks a lot.
